---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   repository: ci-registry.ngrok.io:80/portal-proxy-test
   tag: "latest"
   insecure_registries: [ "ci-registry.ngrok.io:80" ]

run:
  path: sh
  args:
    - -exc
    - |
      cd stratos-ui
      npm install
      npm run test-backend