FROM nginx

RUN mkdir -p /etc/secrets/ && chmod 0600 /etc/secrets
COPY ./certs/pproxy.key /etc/secrets/server.key
COPY ./certs/pproxy.crt /etc/secrets/server.crt
RUN chmod 0600 /etc/secrets/server.key && \
  chmod 0600 /etc/secrets/server.crt

COPY ./conf/nginx.dev.conf /etc/nginx/nginx.conf

EXPOSE 80 443
CMD [ "nginx", "-g", "daemon off;" ]
